### ISSUE TITLE
Return asyncFuncion response after I call region.loadBy

### ISSUE THREAD

**Issue by yixiaojiu** [regionjs/region-core#96]
**Describe the solution you'd like**

Maybe, I want to use asyncFuncion response when I call `region.loadBy`. For example:
```js
import {createRegion} from 'region-core';
import {useEffect} from 'react'
const region = createRegion<User>();
const loadUser = region.loadBy(asyncFuncion);

const Component = () => {
    const value = region.useValue();
    useEffect(() => {
        const fn = async () => {
            const response = await loadUser({userId: 1});
            // I want to use the response here
        }
        fn()
    }, [])
    return <div>...</div>;
}
```
I have the insterest to achieve this. 😉

**Comment by dancerphil** [comment]
### 应该怎么写？

```typescript
const fn = async () => {
    await loadUser({userId: 1});
    const response = region.getValue();
    // I want to use the response here
}
```

### 为什么没有这个功能，我是如何考虑的

实现这个功能的主要问题在于这里的返回不太好给出一个**完美**的定义，所以选择返回了 void。我把一些需要考虑的东西写在下面，可以讨论一下。

1. `loadUser` ，在函数式编程的概念里面，是副作用，即它的功能是发起一次请求的动作，请求本身可能成功或失败，但这个动作本身是不会失败的，也就是说 `loadUser` 从来不会 throw。
2. 所以，如果这里要返回数据的话，应该返回哪种结果
	1. 返回本次触发的请求的返回，如果本次请求失败了，或者本次请求被取消了，则返回 undefined。
	2. 返回本次触发的请求的返回，如果本次请求失败了，或者本次请求被取消了，则返回上次成功的值，如果没有再返回 fallback 值。
3. 在这两种之间，用户很难明白到底返回值采用了哪种策略，在用户不知情的情况下，很容易引起潜藏的 bug，并且难以 debug。
4. 但如果我们使用 `region.getValue` 获取值的时候，含义就会更加明确，即获取在 await 后的 region 中的值，代码也容易理解和 debug。
5. 最后是一些原则性的考虑，我认为 `loadUser` 作为副作用，就让它成为一个纯的副作用，而不返回任何值，这样更符合我对于副作用的理解。

如果有更好的方案可以在这里讨论。

---
### How to implement your logic?

```typescript
const fn = async () => {
    await loadUser({userId: 1});
    const response = region.getValue();
    // I want to use the response here
}
```

### Why this feature is not implemented?

The main concern about this feature is that the return value of `loadUser` cannot be **perfectly** defined. So I choose to return void here. These concerns are listed below:

1. `loadUser` is an effect in `functional programming`. It represents an action of start a fetching and deal with its result. The fetching maybe resolved or rejected, but `loadUser`, which represents an action, will never fail, which means that `loadUser` will not throw.
2. So if we want to defined this return value, it could be defined as two meanings:
	1. return result of this fetching if it is resolved, or return undefined if it is rejected.
	2. return result of this fetching if it is resolved, or return the snapshot value if it is rejected.
3. With two possible meanings, developer can hardly know which meanings we choose. So the confusing leads to hidden bug which is hardly to debug.
4. But when we use `region.getValue`, the meaning is accurate, which is to get the current value in region. So the code will be easy to understand and debug.
5. At last, since `loadUser` is an effect, I want to make sure it is `pure effect`, which means it will not return any value.

Tell me if you have better solution.
